### PR TITLE
First round of improvements on stats page

### PR DESCRIPTION
**Pull request by jotegui**
Basically look'n'feel. Same stats, same stats generation code (almost).
Changes: apply bootstrap style, add a navigation side bar.
See attached screenshot or live preview in 'stats' version of the portal: http://stats.vertnet-portal.appspot.com/stats
screenshot from 2015-04-21 12 29 37

### CODE REVIEW

**Comment by robgur** [comment]
Javi, major improvement.  I'd say we should implement it ASAP. Can I
forward on to whole VN team (not sure everyone gets github notifications?).
-r

**Comment by jotegui** [comment]
Sure. Are you guys still using basecamp? If so, I can send a general update...



—
Enviado desde Mailbox

**Comment by robgur** [comment]
Naw lemme just forward it to all via email... (or you can?)

**Comment by jotegui** [comment]
Go ahead, while I'm having lunch :)

**Comment by laurarussell** [comment]
Looks good to me.  Indicates it can be automatically merged.  So Merging.

**Comment by robgur** [comment]
Super!

**Pull request merged**
