### PR TITLE
New index entry for the usage stats

### PR DESCRIPTION
**Pull request by jotegui**

### CODE REVIEW

**Comment by jotegui** [comment]
FYI, index already deployed to avoid usage reports viewer crashing. It is currently being used, at the time of writing this

**Comment by robgur** [comment]
looks like success on reports from what I am seeing.  Nice!

**Comment by jotegui** [comment]
It does to me too, yes :)

This was supposed to have happened yesterday but, for several
"cartodb-is-killing-my-queries-but-I-don't-want-to-complain-because-I-don't-want-to-look-like-a-whiner"
reasons, it end up happening today. Thank gawd the story ended happily...

Cheers!


*--Javier Otegui* - PGPID: AA372F68
http://www.jotegui.com

**Comment by jotegui** [comment]
Looks like the index was already merged via a previous pull request. Sorry!

**Pull request closed without merging**
